### ISSUE TITLE
Translation of parser output to FOL

### ISSUE THREAD

**Issue by mpertierra** [sivareddyg/graph-parser#3]
Is there a simple way to translate the GraphParser's output to First Order Logic expressions? For example, a translation that would result in an expression that is readable by NLTK's logic module?

**Comment by sivareddyg** [comment]
Unfortunately no. You might want to check out https://github.com/sivareddyg/udeplambda which also produces logical forms. You should be able to write a convertor to convert these to NLTK logical forms. Might be very useful indeed.
