### ISSUE TITLE
Different graph parsing result from online demo and local runs

### ISSUE THREAD

**Issue by Zhenshan-Jin** [sivareddyg/graph-parser#5]
Hi Siva,

When I try to run the graph-parser locally in my computer(with the release in 06/15/2015), I found out that the result from the online demo(http://sivareddy.in/graphparser.html) is different with the one that I get from the release, for which most of the time, the online demo is better than the release.
**example sentence**
Give price and size result for all produced sold between year AAA and BBB
**local result**
![image](https://user-images.githubusercontent.com/14370804/34345805-7a962332-e9b7-11e7-8bc4-71337e6e544a.png)
**online demo**
![image](https://user-images.githubusercontent.com/14370804/34345826-9f17503c-e9b7-11e7-857e-9db749ae39bf.png)

BTW, I tried to build the graph-parser from the master branch, however, I can't get the parsing result, except `Semantic Parse`(no `Words`, `Edges`, `Types`, etc.)
![image](https://user-images.githubusercontent.com/14370804/34345718-aab70a50-e9b6-11e7-95fb-320616d8b793.png)
The `Semantic Parse` result is the same as the online demo, which is almost perfect to build the QA system on top of it. Appreciate it, thanks!

Cheers,
Zhenshan

**Comment by sivareddyg** [comment]
Its been long that I don't remember what is different, but the output will not be drastically different. Only few rules must be different. Hope you figured it out.

**Comment by PonyCheng** [comment]
Yes, I got the same issues. The online demo is shut now so I can't check it. if I run the master branch, I can't get the parsing result, except Semantic Parse(no Words, Edges, Types, etc.) too.
How do you solved it?

**Comment by Sdfabio0** [comment]
Hi great paper btw.
Is it possible to know where the output will be stored after I run the command:
**cat input.txt | sh run.sh** 
In my input files I have all the original sentences but when running the command no output at all
