### ISSUE TITLE
online demo doesn't work

### ISSUE THREAD

**Issue by fogside** [sivareddyg/graph-parser#6]
You see the python error if you will try a [demo](http://sivareddy.in/graphparser.html).

**Comment by sivareddyg** [comment]
@fogside the demo is down since two days I think. The demo runs on Edinburgh servers and I realized my account has been deactivated. Please be patient until I get it back. btw do you use the demo actively. if so for what?

**Comment by BrazilForever11** [comment]
Demo is still down. I am interested to try.

**Comment by sivareddyg** [comment]
sorry, this is no longer supported.
